name: Patch vbmeta and vbmeta_system (Custom Script)

on:
  push:
    paths:
      - 'input/**'
      - 'patch_vbmeta_custom.py'
  workflow_dispatch:

jobs:
  patch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Prepare environment
      run: |
        sudo apt update
        sudo apt install -y python3
        mkdir -p output

    - name: Patch vbmeta.img
      if: ${{ hashFiles('input/vbmeta.img') != '' }}
      run: |
        python3 patch_vbmeta_custom.py input/vbmeta.img output/vbmeta_patched.img

    - name: Patch vbmeta_system.img
      if: ${{ hashFiles('input/vbmeta_system.img') != '' }}
      run: |
        python3 patch_vbmeta_custom.py input/vbmeta_system.img output/vbmeta_system_patched.img

    - name: Upload patched images
      uses: actions/upload-artifact@v4
      with:
        name: patched-vbmeta
        path: output/*.img
